service: nighmare-webhook-listener

plugins:
  - serverless-offline
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 300

functions:
  nightmareWebhookListener:
    handler: handler.nightmareWebhookListener
    events:
      - http:
          path: upload
          method: post
          cors: true