service: nighmare-webhook-listener

plugins:
  - serverless-offline
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true


provider:
  name: aws
  runtime: nodejs6.10
  timeout: 100

functions:
  nightmareWebhookListener:
    handler: handler.nightmareWebhookListener
    events:
      - cloudwatchLog: '/aws/lambda/nighmare-webhook-listener-dev-nightmareWebhookListener'
      - http:
          path: upload
          method: post
          cors: true